feat(rpc): Add RPC endpoint for Fungible Tokens
hirosystems/stacks-subnets pull request #209
Opened 2023-02-08 19:04 UTC by fpbgg

### Description

### Applicable issues
- fixes #164

### Additional info (benefits, drawbacks, caveats)

### Checklist
- [x] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

2023-02-17 02:00 UTC, obycode commented
How is this coming along @fpbgg? Is it ready for review? Can I help get this PR over the finish line tomorrow?

2023-02-17 15:47 UTC, fpbgg commented
Thanks @obycode I was trying to figure out all the warnings and then realized they were caused by one error I had introduced in the unit test code.

2023-02-17 18:14 UTC, obycode commented
> trying to figure out all the warnings

There are a bunch of warnings from merging the stacks-node changes over that need to be cleaned up. Don't worry about those for now. We can tackle those after this round of tasks.

2023-02-17 22:58 UTC, obycode requested changes
Thanks @fpbgg. This is looking good. The main change I'd like to request is to use `amount` in place of `id` everywhere that is referencing FTs. I also need to review your changes in the tests farther.

2023-02-17 22:58 UTC, obycode commented on src/net/http.rs
> +                "Invalid Http request: expected 0-length body for GetAccount".to_string(),
```suggestion
                "Invalid Http request: expected 0-length body for GetNFTWithdrawal".to_string(),
```

2023-02-17 22:58 UTC, obycode commented on src/net/http.rs
> +        let id = u128::from_str(&captures["id"])
Let's make this `amount` for FTs instead of `id`.

2023-02-17 22:58 UTC, obycode commented on src/net/http.rs
> +                "Invalid Http request: expected 0-length body for GetAccount".to_string(),
I just noticed `parse_get_nft_withdrawal` has this wrong too. Can you update that as well while you're in here?

2023-02-22 16:41 UTC, obycode commented
#218 has the remaining fixes for this.

2023-02-22 16:41 UTC, closed without merging